##
## EPITECH PROJECT, 2018
## 
## File description:
## 
##

all:
	cp challenge01.py challenge01
	cp challenge02.py challenge02
	cp challenge03.py challenge03
	cp challenge04.py challenge04
	cp challenge05.py challenge05
	cp challenge07.py challenge07

clean:
	rm challenge01
	rm challenge02
	rm challenge03
	rm challenge04
	rm challenge05
	rm challenge07

fclean:
	rm challenge01
	rm challenge02
	rm challenge03
	rm challenge04
	rm challenge05
	rm challenge07
